---

- name: Make sure cmdtest is removed
  apt: name="cmdtest" state=absent
  when: ansible_os_family == "Debian"
  tags: [packages]

- name: Add the yarn signing keys
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add yarn repo
  apt_repository: repo='deb https://dl.yarnpkg.com/debian/ stable main' state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install the yarn tools (APT)
  apt: name="yarn" state=present update_cache=yes
  when: ansible_os_family == "Debian"
  tags: [packages]
