---

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Make sure cmdtest is removed
  apt: name="cmdtest" state=absent
  when: ansible_os_family == "Debian"
  tags: [packages]

- name: Add the yarn signing keys
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add yarn repo
  apt_repository: repo='deb https://dl.yarnpkg.com/debian/ stable main' state=present update_cache=yes
  when: ansible_os_family == "Debian"

- name: Install the yarn tools (APT)
  apt: name="yarn" state=present update_cache=yes
  when: ansible_os_family == "Debian"
  tags: [packages]

#- name: Set timezone variables
#  copy: content="{{ PROJECT_TIMEZONE }}"
#        dest="{{ timezone_destination_path }}"
#        owner=root
#        group=root
#        mode=0644
#        backup=yes
#  notify:
#    - update timezone


#sudo apt-get remove cmdtest
#curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
#echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
#sudo apt-get update && sudo apt-get install yarn