---
# tasks file for varnish

- name: Add Varnish apt key
  apt_key: url=https://packagecloud.io/varnishcache/varnish41/gpgkey state=present

- name: Add Varnish apt repository
  apt_repository:
    repo: 'deb https://packagecloud.io/varnishcache/varnish41/debian/ stretch main'
    state: present

- name: Install Varnish packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - varnish
    - varnish-modules

- name: create systemd override directory
  file:
    path: /etc/systemd/system/varnish.service.d
    state: directory

- name: add systemd override
  template: src=override.conf.j2 dest=/etc/systemd/system/varnish.service.d/override.conf owner=root group=root mode=0644
  notify: restart varnish

- name: Update update-rc.d
  shell: update-rc.d varnish defaults
  become: yes

- name: Copy Varnish default VCL.
  copy: src="varnish4_xkey.vcl"
        dest="{{ VARNISH_CONFIG_PATH }}/default.vcl"
        backup=yes
        owner=root
        group=root
        mode=0644
  notify: restart varnish

- name: Copy Varnish parameters VCL.
  template: src=parameters.vcl.j2 dest="{{ VARNISH_CONFIG_PATH }}/parameters.vcl" owner=root group=root mode=0644
  notify: restart varnish
