---
# tasks file for composer

- name: Download composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
         creates=/usr/local/bin/composer
  when: ansible_os_family == "Debian"
  tags: [packages,composer]
  args:
      warn: false

- name: Check the composer installation
  command: composer -V --no-ansi
  register: composer_result
  changed_when: "'Composer version' in composer_result.stdout"
  failed_when: "'Composer version' not in composer_result.stdout"
  when: ansible_os_family == "Debian"
  tags: [packages,composer]
